# site settings
title: cdf1982
subtitle:
email: support@cdf1982.com
description: Ciao, Iâ€™m Cesare. Thanks for visiting my website!<br />Here youâ€™ll find information about my Mac and iOS applications, and itâ€™s also where I sometimes blog about software development, Apple and other things I find interesting.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://cdf1982.com
author: Cesare Forelli
street_address:
city:
state:
zip_code:
country: In sunny Italy  â˜€ï¸ ğŸ‡®ğŸ‡¹
phone:
plugins:
  - jekyll-feed

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url:
github_url: https://github.com/cdf1982
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/cdf1982

# build settings
markdown: kramdown
exclude: [/_workingfiles]

sass:
  style: compressed
