# site settings
title: cdf1982.com
subtitle:
email: support@cdf1982.com
description: Ciao, Iâ€™m Cesare. I'm an indie Mac and iOS developer and this is the home for my apps and blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://cdf1982.com
author: Cesare Forelli
street_address:
city:
state:
zip_code:
country: In sunny Italy  â˜€ï¸ ğŸ‡®ğŸ‡¹
phone:
plugins:
  - jekyll-feed
  - jekyll-sitemap

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url:
github_url: https://github.com/cdf1982
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/millakillapilla/
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/cdf1982

# build settings
markdown: kramdown
highlighter: rouge
exclude: [/_workingfiles]

sass:
  style: compressed
